{{- if .Values.app.ingress.enabled -}}
{{- $apiIsStable := eq (include "backstage.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "backstage.ingress.supportsPathType" .) "true" -}}
{{- $serviceName := include "backstage.appFullname" . -}}
{{- $servicePort := .Values.app.service.port -}}
apiVersion: {{ include "backstage.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "backstage.appLabels" . | nindent 4 }}
  {{- with .Values.app.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if and $apiIsStable .Values.app.ingress.ingressClassName }}
  ingressClassName: {{ .Values.app.ingress.ingressClassName }}
{{- end }}
  rules:
  {{- range .Values.app.ingress.hosts }}
    - host: {{ quote . }}
      http:
        paths:
          - path: /
            {{- if $ingressSupportsPathType }}
            pathType: Prefix
            {{- end }}
            backend:
            {{- if $apiIsStable }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: http
            {{- end }}
  {{- end }}
  {{- if .Values.app.ingress.tls }}
  tls:
  {{- range .Values.app.ingress.tls }}
    - hosts:
    {{- range .hosts }}
        - {{ quote . }}
    {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
{{- end }}
