apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "backstage.backendConfigName" . }}
  labels:
    {{- include "backstage.backendLabels" . | nindent 4 }}
data:
  app-config.yaml: |
    {{- .Values.appConfig | toYaml | nindent 4 }}
