{{- if .Values.backend.podDisruptionBudget.enabled -}}
apiVersion: {{ include "backstage.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "backstage.backendFullname" . }}
  labels:
    {{- include "backstage.backendLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "backstage.backendSelectorLabels" . | nindent 6 }}
{{- if .Values.backend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
{{- end  }}
{{- if .Values.backend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.backend.podDisruptionBudget.maxUnavailable }}
{{- end  }}
{{- end -}}
