apiVersion: v2
name: backstage
description: A Helm chart for the Backstage

type: application

version: 0.0.2
appVersion: "0.0.2"

home: "https://blog.bradmccoy.io"
icon: https://backstage.io/img/twitter-summary.png
sources:
  - "https://github.com/bradmccoydev/backstage-chart"
annotations:
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/links: |
    - name: support
      url: https://github.com/bradmccoydev/backstage-chart/issues
keywords:
  - cloud-native
  - microservice
  - cd
  - bradmccoydev
  - catalog
maintainers:
- email: bradmccoydev@gmail.com
  name: bradmccoydev
